### ISSUE TITLE
What's the performance like?

### ISSUE THREAD

**Issue by dimraft** [rreilink/PiPyOS#2]
Hi, I came across this project and am really interested in it.

Do you have any data yet on what the performance is like? Do you get faster execution or lower latency  GPIO when using this rather than running Python on top of RaspbianOS?

I'm specifically interested in whether this could be used to implement realtime IO behaviour on the RaspberryPI in Python, e.g. generating pulses, or responding very quickly to external IO signals (within microseconds).

Sorry for raising an Issue ticket, but I could not figure out how else to contact you on GitHub.

Thanks!

**Comment by rreilink** [comment]
Performance is exactly the reason why I started PiPyOS. The ARM core has two interrupt levels: IRQ and FIQ (Fast IRQ). The FIQ can interrupt the IRQ. PiPyOS only uses the IRQ, so FIQ can be used by the user, and never needs to be disabled. This means guaranteed low latency.

I have achieved <100ns jitter at 100kHz timer interrupts, and lower / faster might well be possible. You could even use the TCM (tightly coupled memory) feature of the ARM core to prevent latency due to cache-misses, but that would require quite some digging into the ARM core specification, and I have not yet found the need for higher performance than is currently achieved.

I am currently using PiPyOS to generate >100kHz step/direction signals for a 7-axis stepper controller.
